### ISSUE TITLE
missing codemining-utils dependency

### ISSUE THREAD

**Issue by stevenpjg** [mast-group/codemining-core#1]
When I installed this project via maven-install it throws me the following error:

[ERROR] Failed to execute goal on project codemining-core: Could not resolve dependencies for project codemining:codemining-core:jar:1.1-SNAPSHOT: Failure to find codemining:codemining-utils:jar:1.1-SNAPSHOT in https://github.com/mast-group/maven-repo/tree/master/repository was cached in the local repository, resolution will not be reattempted until the update interval of maven-repo has elapsed or updates are forced -> [Help 1]

Also, do you have any example code snippets for tokenizing and finding ASTs in python codes? Thanks.

**Comment by mallamanis** [comment]
Hi Steven,
The `codemining-utils` repository can be found [here](https://github.com/mast-group/codemining-utils). I've made the projects as maven submodules that you can use in your own code, so you would need to include both in your project's module.

Regarding, code for tokenizing Python code, you can see the main in [TokenizerTUI](https://github.com/mast-group/codemining-core/blob/master/src/main/java/codemining/languagetools/tui/TokenizerTUI.java) and use th appropriate tokenizer class from [here](https://github.com/mast-group/codemining-core/tree/master/src/main/java/codemining/python/codeutils).

Unfortunately, you cannot extract Python ASTs with the Java code. The best options include Python's [ast](https://docs.python.org/3.4/library/ast.html) module or [astroid](https://github.com/PyCQA/astroid). The code here only supports Java and Javascript (through Eclipse's APIs).
